- hosts: localhost
  connection: local
  become: true

  pre_tasks:
      - name: update reporistories
        pacman:
            update_cache: yes
        changed_when: false

  tasks:
      - include: tasks/packages.yml
